"""empty message

Revision ID: 321cbfeaa0a6
Revises: ad80a5857c36
Create Date: 2018-01-15 19:26:48.735853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '321cbfeaa0a6'
down_revision = 'ad80a5857c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_column('bucketlists', 'datecreated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('datecreated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('bucketlists', 'date_created')
    # ### end Alembic commands ###
