"""empty message

Revision ID: 352b8aa92ecc
Revises: 242ba6319810
Create Date: 2018-01-07 09:00:04.126146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352b8aa92ecc'
down_revision = '242ba6319810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bucketlists_name_key', 'bucketlists', type_='unique')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_unique_constraint('bucketlists_name_key', 'bucketlists', ['name'])
    # ### end Alembic commands ###
