"""empty message

Revision ID: 80fe04980dbd
Revises: 9168e8d814a0
Create Date: 2017-10-11 15:13:51.378162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80fe04980dbd'
down_revision = '9168e8d814a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bucketlists', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bucketlists', type_='foreignkey')
    op.drop_column('bucketlists', 'user_id')
    # ### end Alembic commands ###
