"""empty message

Revision ID: ad80a5857c36
Revises: 352b8aa92ecc
Create Date: 2018-01-15 19:26:12.859909

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad80a5857c36'
down_revision = '352b8aa92ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('datecreated', sa.DateTime(), nullable=True))
    op.drop_column('bucketlists', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlists', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('bucketlists', 'datecreated')
    # ### end Alembic commands ###
